# Auto generated, do not edit.

PRODUCT_COPY_FILES += \
    prebuilts/beach/fdroid/fallback-icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/fallback-icon.png \
    prebuilts/beach/fdroid/repo/app.organicmaps/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/app.organicmaps/en-US/icon.png \
    prebuilts/beach/fdroid/repo/at.bitfire.davdroid/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/at.bitfire.davdroid/en-US/icon.png \
    prebuilts/beach/fdroid/repo/categories.txt:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/categories.txt \
    prebuilts/beach/fdroid/repo/com.artifex.mupdf.viewer.app/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.artifex.mupdf.viewer.app/en-US/icon.png \
    prebuilts/beach/fdroid/repo/com.aurora.store/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.aurora.store/en-US/icon.png \
    prebuilts/beach/fdroid/repo/com.fsck.k9/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.fsck.k9/en-US/icon.png \
    prebuilts/beach/fdroid/repo/com.jarsilio.android.scrambledeggsif/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.jarsilio.android.scrambledeggsif/en-US/icon.png \
    prebuilts/beach/fdroid/repo/com.nextcloud.client/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.nextcloud.client/en-US/icon.png \
    prebuilts/beach/fdroid/repo/entry.jar:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/entry.jar \
    prebuilts/beach/fdroid/repo/entry.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/entry.json \
    prebuilts/beach/fdroid/repo/icons-120/org.beachinstitute.vpn.160000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/org.beachinstitute.vpn.160000.png \
    prebuilts/beach/fdroid/repo/icons-120/se.leap.riseupvpn.162000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/se.leap.riseupvpn.162000.png \
    prebuilts/beach/fdroid/repo/icons-160/org.beachinstitute.vpn.160000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/org.beachinstitute.vpn.160000.png \
    prebuilts/beach/fdroid/repo/icons-160/se.leap.riseupvpn.162000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/se.leap.riseupvpn.162000.png \
    prebuilts/beach/fdroid/repo/icons-240/org.beachinstitute.vpn.160000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/org.beachinstitute.vpn.160000.png \
    prebuilts/beach/fdroid/repo/icons-240/se.leap.riseupvpn.162000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/se.leap.riseupvpn.162000.png \
    prebuilts/beach/fdroid/repo/icons-320/org.beachinstitute.vpn.160000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/org.beachinstitute.vpn.160000.png \
    prebuilts/beach/fdroid/repo/icons-320/se.leap.riseupvpn.162000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/se.leap.riseupvpn.162000.png \
    prebuilts/beach/fdroid/repo/icons-480/org.beachinstitute.vpn.160000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/org.beachinstitute.vpn.160000.png \
    prebuilts/beach/fdroid/repo/icons-480/se.leap.riseupvpn.162000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/se.leap.riseupvpn.162000.png \
    prebuilts/beach/fdroid/repo/icons-640/org.beachinstitute.vpn.160000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/org.beachinstitute.vpn.160000.png \
    prebuilts/beach/fdroid/repo/icons-640/se.leap.riseupvpn.162000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/se.leap.riseupvpn.162000.png \
    prebuilts/beach/fdroid/repo/icons/fdroid-icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/fdroid-icon.png \
    prebuilts/beach/fdroid/repo/icons/org.beachinstitute.vpn.160000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/org.beachinstitute.vpn.160000.png \
    prebuilts/beach/fdroid/repo/icons/se.leap.riseupvpn.162000.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/se.leap.riseupvpn.162000.png \
    prebuilts/beach/fdroid/repo/index.css:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.css \
    prebuilts/beach/fdroid/repo/index.html:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.html \
    prebuilts/beach/fdroid/repo/index.jar:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.jar \
    prebuilts/beach/fdroid/repo/index.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.png \
    prebuilts/beach/fdroid/repo/index-v1.jar:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index-v1.jar \
    prebuilts/beach/fdroid/repo/index-v1.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index-v1.json \
    prebuilts/beach/fdroid/repo/index-v2.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index-v2.json \
    prebuilts/beach/fdroid/repo/index.xml:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.xml \
    prebuilts/beach/fdroid/repo/org.briarproject.briar.android/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.briarproject.briar.android/en-US/icon.png \
    prebuilts/beach/fdroid/repo/org.beachinstitute.vpn/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.beachinstitute.vpn/en-US/icon.png \
    prebuilts/beach/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon.png \
    prebuilts/beach/fdroid/repo/org.thoughtcrime.securesms/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.thoughtcrime.securesms/en-US/icon.png \
    prebuilts/beach/fdroid/repo/org.torproject.android/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.torproject.android/en-US/icon.png \
    prebuilts/beach/fdroid/repo/org.torproject.torbrowser/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.torproject.torbrowser/en-US/icon.png \
    prebuilts/beach/fdroid/repo/se.leap.riseupvpn/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/se.leap.riseupvpn/en-US/icon.png \
    prebuilts/beach/fdroid/repo/status/running.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/status/running.json \
    prebuilts/beach/fdroid/repo/status/update.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/status/update.json \
    prebuilts/beach/fdroid/repo/wangdaye.com.geometricweather/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/wangdaye.com.geometricweather/en-US/icon.png \

PRODUCT_PACKAGES += \
    fdroid-repo \
    AuroraStore \
    Briar \
    BeachVPN \
    DAVx5 \
    GeometricWeather \
    K-9Mail \
    MuPDFviewer \
    Nextcloud \
    OONIProbe \
    Orbot \
    OrganicMaps \
    RiseupVPN \
    ScrambledExif \
    Signal \
    TorBrowser \
